# Generated by Django 6.0.6 on 2026-06-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='rack_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
