# Generated by Django 6.0.6 on 2026-06-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_invalidate_low_confidence_geocodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('source', models.CharField(default='us_cities_dataset', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='coordinate_quality',
            field=models.CharField(choices=[('high', 'High Quality'), ('medium', 'Medium Quality'), ('approximate', 'Approximate (City Centroid)'), ('unknown', 'Unknown Quality')], default='unknown', help_text='Quality/accuracy of coordinates', max_length=20),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='coordinate_source',
            field=models.CharField(choices=[('exact_station', 'Exact Station Location'), ('city_centroid', 'City Centroid (Approximate)'), ('manual', 'Manual Coordinates'), ('unknown', 'Unknown Source')], default='unknown', help_text='Source of station coordinates', max_length=20),
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['coordinate_source'], name='api_fuelsta_coordin_38ed1b_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['coordinate_quality'], name='api_fuelsta_coordin_82e581_idx'),
        ),
        migrations.AddIndex(
            model_name='citycoordinate',
            index=models.Index(fields=['city', 'state'], name='api_citycoo_city_70b4d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='citycoordinate',
            constraint=models.UniqueConstraint(fields=('city', 'state'), name='unique_city_state_coordinate'),
        ),
    ]
