"""
Django settings for fuelSpotter project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import math
import os

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    """Read a strict boolean environment value."""
    value = os.environ.get(name)
    if value is None:
        return default
    normalized = value.strip().lower()
    if normalized in {'1', 'true', 'yes', 'on'}:
        return True
    if normalized in {'0', 'false', 'no', 'off'}:
        return False
    raise ImproperlyConfigured(f'{name} must be a boolean value')


def env_list(name, default=None, *, normalize=None):
    """Read a comma-separated environment value without empty entries."""
    raw_value = os.environ.get(name)
    if raw_value is None:
        values = list(default or [])
    else:
        values = [item.strip() for item in raw_value.split(',') if item.strip()]
    if normalize is not None:
        values = [normalize(item) for item in values]
    return values


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Development defaults are intentionally unsuitable for production.
DEBUG = env_bool('DEBUG', True)
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('SECRET_KEY must be set when DEBUG is false')
    SECRET_KEY = 'django-insecure-development-only-change-me'

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', ['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    # Local apps
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fuelSpotter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fuelSpotter.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('SQLITE_PATH', BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URL trailing slash behavior
APPEND_SLASH = True

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', False)
CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# External map services
OSRM_BASE_URL = os.environ.get('OSRM_BASE_URL', 'https://router.project-osrm.org').rstrip('/')
NOMINATIM_BASE_URL = os.environ.get(
    'NOMINATIM_BASE_URL',
    'https://nominatim.openstreetmap.org',
).rstrip('/')
EXTERNAL_HTTP_TIMEOUT_SECONDS = float(os.environ.get('EXTERNAL_HTTP_TIMEOUT_SECONDS', '10'))
NOMINATIM_USER_AGENT = os.environ.get(
    'NOMINATIM_USER_AGENT',
    'FuelSpotter/1.0 (contact: opeyemi655@gmail.com)',
)
NOMINATIM_MIN_INTERVAL_SECONDS = float(
    os.environ.get('NOMINATIM_MIN_INTERVAL_SECONDS', '1')
)
NOMINATIM_TIMEOUT_SECONDS = float(
    os.environ.get('NOMINATIM_TIMEOUT_SECONDS', EXTERNAL_HTTP_TIMEOUT_SECONDS)
)
GEOCODING_STALE_AFTER_SECONDS = float(
    os.environ.get('GEOCODING_STALE_AFTER_SECONDS', '120')
)
GEOCODING_POLL_SECONDS = float(os.environ.get('GEOCODING_POLL_SECONDS', '5'))
GEOCODING_MAX_RETRIES = int(os.environ.get('GEOCODING_MAX_RETRIES', '5'))
FUEL_ROUTE_CORRIDOR_MILES = float(
    os.environ.get('FUEL_ROUTE_CORRIDOR_MILES', '5')
)
if not math.isfinite(FUEL_ROUTE_CORRIDOR_MILES) or FUEL_ROUTE_CORRIDOR_MILES <= 0:
    raise ImproperlyConfigured(
        'FUEL_ROUTE_CORRIDOR_MILES must be positive and finite'
    )
GEOCODING_AUTO_QUEUE_BATCH_SIZE = int(
    os.environ.get('GEOCODING_AUTO_QUEUE_BATCH_SIZE', '500')
)
if GEOCODING_AUTO_QUEUE_BATCH_SIZE <= 0:
    raise ImproperlyConfigured('GEOCODING_AUTO_QUEUE_BATCH_SIZE must be positive')
RUN_APP_ADDRPORT = os.environ.get('RUN_APP_ADDRPORT', '127.0.0.1:8000')
if (
    GEOCODING_STALE_AFTER_SECONDS
    <= NOMINATIM_TIMEOUT_SECONDS + NOMINATIM_MIN_INTERVAL_SECONDS
):
    raise ImproperlyConfigured(
        'GEOCODING_STALE_AFTER_SECONDS must exceed the Nominatim timeout and interval'
    )
SUPPORTED_COUNTRY_CODES = env_list(
    'SUPPORTED_COUNTRY_CODES',
    ['us'],
    normalize=str.lower,
)

# Fixed assumptions from the backend assessment contract.
VEHICLE_MAX_RANGE_MILES = 500
VEHICLE_MPG = 10

# Allow approximate city centroid coordinates for route matching (DEMO ONLY!)
ALLOW_APPROXIMATE_CITY_COORDINATES_FOR_ROUTE_MATCHING = env_bool(
    'ALLOW_APPROXIMATE_CITY_COORDINATES_FOR_ROUTE_MATCHING',
    False
)
